### ISSUE TITLE
[FlexGrid] not updating layout when printing

### ISSUE THREAD

**Issue by lxingtelus** [telusdigital/tds-core#501]
hi guys, so before v1.0 when we had Grid, we were responsive by using media queries and that meant our printed content were laid out correctly respective to the paper width. 

but with FlexGrid, depending on the width of the browser when the user clicks print, the layout stays the same in the print preview (ie. based on browser width, not paper width). This is causing our 2 columns of content to show up side by side on the print instead of stacking like it should and was using width of letter paper.

The best solution i can come up with is in the print css, override flex-basis and max-width for both columns explicitly, and add in appropriate margin bottom. Is there a better solution? thanks

This issue spawned from my question in @tds-support channel on slack. Just logging it here so it's up for discussion.

**Comment by ryanoglesby08** [comment]
Hi @lxingtelus, as of `@tds/core-flex-grid@1.2.0` the grid is back to using media queries for responsive behaviour. Based on your description, I think that should account for this issue without having to override any CSS.

Are you able to confirm?

**Comment by ryanoglesby08** [comment]
We have been able to confirm that layouts are preserved when printing and using FlexGrid.
