### ISSUE TITLE
[ExpandCollapse] content within collapsed Panels can be read/tab-focused

### ISSUE THREAD

**Issue by theetrain** [telusdigital/tds-core#535]
## Description

Originally reported by @owestinTelus 

While an ExpandCollapse component has a collapsed Panel containing a hyperlink, the link is keyboard-focusable. Also, screen readers may read the contents of collapsed Panels.

## Reproduction Steps

1. Go to https://tds.telus.com/components/index.html#!/ExpandCollapse/0
2. Paste the following code
```jsx
<ExpandCollapse>
  <ExpandCollapse.Panel id="features" header="Features">
    <Box between={3}>
      <Box between={2}>
        <Heading level="h4">Connected GPS</Heading>
        <Paragraph size="medium">
          Connect to your phone's GPS to see real-time run stats. <Link href="telus.com">Go to telus</Link>
        </Paragraph>
      </Box>

      <Box between={2}>
        <Heading level="h4">Notifications</Heading>
        <Paragraph size="medium">
          See call, text and calendar alerts on your wrist.
        </Paragraph>
      </Box>
    </Box>
  </ExpandCollapse.Panel>

  <ExpandCollapse.Panel id="specs" header="Specifications">
    <Box between={3}>
      <Box between={2}>
        <Heading level="h4">Display</Heading>
        <Paragraph size="medium">OLED</Paragraph>
      </Box>

      <Box between={2}>
        <Heading level="h4">Battery Life</Heading>
        <Paragraph size="medium">Up to 5 days</Paragraph>
      </Box>
    </Box>
  </ExpandCollapse.Panel>
</ExpandCollapse>
```
3. While all Panels are collapsed, use the keyboard TAB button
4. Observe the hyperlink becomes keyboard-focusable while its parent Panel is collapsed

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: all since ExpandCollapse's first release
* Willing to develop solution: Yes
* Has workaround: No
* High impact: No

## Screenshots

![image](https://user-images.githubusercontent.com/12798751/37798935-979a6340-2df4-11e8-9add-1192a230d4d0.png)

**Comment by ryanoglesby08** [comment]
Fixed in v0.34.13, v1.0.12, `@tds/core-expand-collapse/@1.0.2`
