### ISSUE TITLE
[Input] Flash of content when formatting input value

### ISSUE THREAD

**Issue by ryanoglesby08** [telusdigital/tds-core#606]
## Description

When applying formatting to input values, certain formatting rules can cause race conditions where the state of the Input gets out of sync with the state of the application, causing visual flashes of content.

## Reproduction Steps

Paste this into any react-styleguidist code playground on the TDS component catalogue. The `numbersOnly` change handler should prevent letters from being typed into the input. Instead, letters are entered, and then removed on the next character entered.

```jsx
initialState = {
  value: ''
}

const numbersOnly = event => {
  const noAlpha = event.target.value.replace(/[a-z]/g, "");  
  setState({ value: noAlpha })
}

<Input
  label="Phone number"
  value={state.value}
  onChange={numbersOnly}
/>
```

## Meta

* TDS version: 0.34, 1.0, split components
* Has workaround: No

**Comment by marcod1419** [comment]
Fixed in this release: https://github.com/telusdigital/tds-core/releases/tag/%40tds%2Fshared-form-field%401.0.4
